<?php
/** @var Hvendor\Display\Block\Hello $block */
$cars = $block->getAllCars();
?>

<form method="post" action="<?= $block->getAddCarPostUrl() ?>">
   <fieldset>
       <div>
            <label for="manufacturer"><?= __("Name") ?></label>
           <input type="text" name="name" id="manufacturer" />
      </div>
      <div>
            <label for="manufacturer"><?= __("Email") ?></label>
           <input type="text" name="email" id="manufacturer"/>
      </div>
       <div>
            <label for="model"><?= __("Phone Number") ?></label>
           <input type="text" name="phone" id="model" />
       </div>
      <input type="submit" value="<?= __("Add Details") ?>" />
   </fieldset>
</form>
<hr />
<?php if (count($cars) > 0): ?>
 <table border="1">
      <tr>
         <th><?= __("ID") ?></th>
          <th><?= __("Name") ?></th>
            <th><?= __("Email") ?></th>
            <th><?= __("Phone") ?></th>
        </tr>
       <?php foreach ($cars as $car): ?>
            <tr>
               <td><?= $car->getId() ?></td>
               <td><?= $car->getName() ?></td>
              <td><?= $car->getEmail() ?></td>
              <td><?= $car->getPhone() ?></td>

           </tr>
      <?php endforeach; ?>
    </table>
<?php else: ?>
    <h1><?= __("You have no cars yet :(") ?></h1>
<?php endif; ?>