<div class="someclass">
    <h1>List of Pages</h1>
<ul>

    <li><a href="<?= $block->getUrl('display/factory/fwdfactory',['prg'=>'p4'])?>">Forward Factory</a></li>
    <li><a href="<?= $block->getUrl('display/factory/redirectfactory',['prg'=>'p4'])?>">Redirect Factory</a></li>


    <li><a href="<?= $block->getUrl('display/productcrud/withpagefactory',['prg'=>'p1'])?>">Product crud with pagefactory</a></li>
    <li><a href="<?= $block->getUrl('display/productcrud/withoutpagefactory',['prg'=>'p2'])?>">Product crud without pagefactory</a></li>
    <li><a href="<?= $block->getUrl('display/kanbon/kanbon',['prg'=>'p3'])?>">Kanbon and RandomColor Generator</a></li>
    <li><a href="<?= $block->getUrl('display/index/Index',['prg'=>'p4'])?>">Model</a></li>
</ul>





</div>